/**
 * Receitas brasileiras — regionais e por refeição.
 * images: Unsplash (uso em demo pessoal)
 */
var RECIPES = [
  /* ─── CAFÉ DA MANHÃ ─── */
  {
    id: "cuscuz-manteiga-ovo",
    name: "Cuscuz nordestino com manteiga e ovo",
    meals: ["cafe"],
    region: "nordeste",
    state: "sergipe",
    tags: ["cuscuz", "manteiga", "ovo", "farinha"],
    shop: ["cuscuz de milho", "manteiga", "ovos", "sal"],
    image: "https://images.unsplash.com/photo-1482049016688-2d3e1b311543?w=800&q=80",
    time: "20 min",
    level: "Fácil",
    origin: "Nordeste · Sergipe",
    desc: "Clássico café da manhã sergipano: cuscuz soltinho, ovo frito ou cozido e manteiga derretida.",
    steps: [
      "Umedeça o cuscuz com água e sal; deixe hidratar 5 min.",
      "Coloque na cuscuzeira ou panela com furo e cozinhe no vapor por 10–12 min.",
      "Desenforme o cuscuz ainda quente.",
      "Frite ou cozinhe os ovos ao seu gosto.",
      "Sirva com manteiga derretida por cima.",
    ],
  },
  {
    id: "pao-manteiga-cafe",
    name: "Pão na chapa com manteiga e café coado",
    meals: ["cafe"],
    region: "brasil",
    tags: ["pao", "manteiga", "cafe", "leite"],
    shop: ["pão francês ou de forma", "manteiga", "café", "leite", "açúcar"],
    image: "https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?w=800&q=80",
    time: "10 min",
    level: "Fácil",
    origin: "Brasil",
    desc: "Café da manhã universal: pão tostado na manteiga e café quente com leite.",
    steps: [
      "Corte o pão e passe manteiga dos dois lados.",
      "Doure na frigideira ou sanduicheira até ficar crocante.",
      "Prepare o café coado ou passado.",
      "Adoce o café com leite e açúcar a gosto.",
      "Sirva o pão quente acompanhando o café.",
    ],
  },
  {
    id: "tapioca-queijo",
    name: "Tapioca com queijo e manteiga",
    meals: ["cafe", "janta"],
    region: "nordeste",
    tags: ["tapioca", "queijo", "manteiga"],
    shop: ["goma de tapioca", "queijo coalho ou mussarela", "manteiga"],
    image: "https://images.unsplash.com/photo-1567620905732-2d1ec7ab7445?w=800&q=80",
    time: "8 min",
    level: "Fácil",
    origin: "Nordeste",
    desc: "Tapioca rápida, recheada com queijo derretido — perfeita para café ou lanche noturno.",
    steps: [
      "Aqueça a frigideira antiaderente.",
      "Espalhe a goma de tapioca em movimento circular fino.",
      "Quando firmar, vire e adicione o queijo.",
      "Dobre ao meio e doure dos dois lados.",
      "Passe manteiga por cima e sirva quente.",
    ],
  },
  {
    id: "ovos-mexidos-pao",
    name: "Ovos mexidos com pão e biscoito",
    meals: ["cafe"],
    region: "brasil",
    tags: ["ovo", "pao", "biscoito", "manteiga"],
    shop: ["ovos", "manteiga", "pão", "biscoito", "sal"],
    image: "https://images.unsplash.com/photo-1525351484163-7529414344d8?w=800&q=80",
    time: "12 min",
    level: "Fácil",
    origin: "Brasil",
    desc: "Ovos cremosos na manteiga, pão torrado e biscoito para acompanhar.",
    steps: [
      "Bata levemente os ovos com sal.",
      "Derreta manteiga em fogo baixo e adicione os ovos.",
      "Mexa devagar até ficarem cremosos.",
      "Toste o pão na manteiga.",
      "Sirva com biscoitos ao lado.",
    ],
  },
  {
    id: "mingau-milho",
    name: "Mingau de milho (canjica doce)",
    meals: ["cafe"],
    region: "nordeste",
    state: "sergipe",
    tags: ["doce", "leite", "farinha", "cuscuz"],
    shop: ["milho branco ou canjica", "leite", "açúcar", "canela", "cravo"],
    image: "https://images.unsplash.com/photo-1525351484163-7529414344d8?w=800&q=80",
    time: "45 min",
    level: "Médio",
    origin: "Nordeste",
    desc: "Mingau cremoso de milho, tradicional em festas juninas e cafés de fim de semana.",
    steps: [
      "Deixe o milho de molho de um dia para o outro (ou use panela de pressão).",
      "Cozinhe o milho até ficar macio.",
      "Adicione leite, açúcar, canela e cravo.",
      "Cozinhe em fogo baixo mexendo até engrossar.",
      "Sirva quente com canela polvilhada.",
    ],
  },
  {
    id: "cafe-leite-biscoito",
    name: "Café com leite e biscoitos",
    meals: ["cafe"],
    region: "brasil",
    tags: ["cafe", "leite", "biscoito"],
    shop: ["café", "leite", "biscoito maizena ou cream cracker", "açúcar"],
    image: "https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?w=800&q=80",
    time: "5 min",
    level: "Fácil",
    origin: "Brasil",
    desc: "O café mais simples: quente, com leite e biscoito para molhar.",
    steps: [
      "Prepare café forte coado ou passado.",
      "Aqueça o leite (sem ferver).",
      "Misture café e leite na proporção que preferir.",
      "Adoce a gosto.",
      "Acompanhe com biscoitos.",
    ],
  },
  {
    id: "crepioca-frango",
    name: "Crepioca de frango",
    meals: ["cafe", "janta"],
    region: "sudeste",
    tags: ["frango", "ovo", "tapioca", "queijo"],
    shop: ["goma de tapioca", "ovos", "frango desfiado", "queijo", "sal", "orégano"],
    image: "https://images.unsplash.com/photo-1565299624946-b28f40a0ae38?w=800&q=80",
    time: "15 min",
    level: "Fácil",
    origin: "Sudeste",
    desc: "Mistura de tapioca e ovo, recheada com frango — prática e proteica.",
    steps: [
      "Misture goma de tapioca, ovo batido e sal.",
      "Despeje na frigideira untada e espalhe.",
      "Recheie com frango desfiado e queijo.",
      "Dobre e doure dos dois lados.",
      "Sirva quente.",
    ],
  },

  /* ─── ALMOÇO ─── */
  {
    id: "baião-dois",
    name: "Baião de dois",
    meals: ["almoco"],
    region: "nordeste",
    state: "ceara",
    tags: ["arroz", "feijao", "queijo", "farinha"],
    shop: ["arroz", "feijão verde ou de corda", "queijo coalho", "coentro", "cebola", "alho"],
    image: "https://images.unsplash.com/photo-1546069901-ba9599a7e63c?w=800&q=80",
    time: "50 min",
    level: "Médio",
    origin: "Nordeste · Ceará",
    desc: "Arroz com feijão verde, queijo coalho e coentro — prato forte do sertão.",
    steps: [
      "Cozinhe o feijão verde até ficar macio.",
      "Refogue cebola e alho, adicione o arroz.",
      "Acrescente o feijão com um pouco do caldo.",
      "Cozinhe até o arroz secar.",
      "Finalize com queijo coalho em cubos e coentro fresco.",
    ],
  },
  {
    id: "moqueca-sergipana",
    name: "Moqueca sergipana de peixe",
    meals: ["almoco"],
    region: "nordeste",
    state: "sergipe",
    tags: ["peixe", "legumes", "arroz", "farinha"],
    shop: ["filé de peixe", "leite de coco", "pimentão", "tomate", "cebola", "coentro", "azeite de dendê", "arroz"],
    image: "https://images.unsplash.com/photo-1519708227418-c8fd9a32b7a2?w=800&q=80",
    time: "40 min",
    level: "Médio",
    origin: "Nordeste · Sergipe",
    desc: "Peixe cozido no leite de coco com legumes — ícone da culinária sergipana.",
    steps: [
      "Tempere o peixe com limão, sal e alho.",
      "Monte camadas de peixe, tomate, pimentão e cebola na panela.",
      "Adicione leite de coco e um fio de dendê.",
      "Cozinhe em fogo baixo por 20–25 min sem mexer muito.",
      "Finalize com coentro e sirva com arroz branco.",
    ],
  },
  {
    id: "feijao-tropeiro",
    name: "Feijão tropeiro mineiro",
    meals: ["almoco"],
    region: "sudeste",
    state: "minas gerais",
    tags: ["feijao", "farinha", "ovo", "carne"],
    shop: ["feijão cozido", "farinha de mandioca", "ovos", "bacon ou linguiça", "couve", "alho"],
    image: "https://images.unsplash.com/photo-1604908176997-125f25cc6f3d?w=800&q=80",
    time: "35 min",
    level: "Médio",
    origin: "Sudeste · Minas Gerais",
    desc: "Feijão batido com farinha, ovos, bacon e couve refogada.",
    steps: [
      "Frite bacon ou linguiça em cubos.",
      "Adicione alho e feijão cozido com um pouco de caldo.",
      "Misture farinha de mandioca aos poucos.",
      "Acrescente ovos mexidos na panela.",
      "Sirva com couve refogada e torresmo se tiver.",
    ],
  },
  {
    id: "galinhada",
    name: "Galinhada",
    meals: ["almoco"],
    region: "centro-oeste",
    tags: ["frango", "arroz", "legumes"],
    shop: ["frango em pedaços", "arroz", "milho verde", "ervilha", "cenoura", "cebola", "alho", "colorau"],
    image: "https://images.unsplash.com/photo-1519708227418-c8fd9a32b7a2?w=800&q=80",
    time: "55 min",
    level: "Médio",
    origin: "Centro-Oeste",
    desc: "Arroz cozido com frango e legumes — almoço completo em uma panela.",
    steps: [
      "Tempere e doure os pedaços de frango.",
      "Refogue cebola, alho e legumes.",
      "Adicione arroz e água ou caldo na proporção correta.",
      "Cozinhe tampado até o arroz secar.",
      "Deixe descansar 5 min antes de servir.",
    ],
  },
  {
    id: "feijoada-completa",
    name: "Feijoada completa",
    meals: ["almoco"],
    region: "sudeste",
    state: "rio de janeiro",
    tags: ["feijao", "carne", "farinha", "arroz"],
    shop: ["feijão preto", "carne seca", "linguiça", "costela", "arroz", "farofa", "couve", "laranja"],
    image: "https://images.unsplash.com/photo-1600891964092-4316c288032e?w=800&q=80",
    time: "2 h",
    level: "Difícil",
    origin: "Sudeste · Rio de Janeiro",
    desc: "O prato mais brasileiro: feijão preto com carnes, arroz, farofa e couve.",
    steps: [
      "Dessalgue as carnes de um dia para o outro.",
      "Cozinhe o feijão com as carnes em fogo baixo.",
      "Prepare arroz branco, couve refogada e farofa.",
      "Ajuste sal e deixe o caldo encorpar.",
      "Sirva com laranja e pimenta.",
    ],
  },
  {
    id: "carne-panela-legumes",
    name: "Carne de panela com legumes",
    meals: ["almoco", "janta"],
    region: "brasil",
    tags: ["carne", "legumes", "arroz"],
    shop: ["carne de patinho ou acém", "batata", "cenoura", "cebola", "tomate", "arroz"],
    image: "https://images.unsplash.com/photo-1600891964092-4316c288032e?w=800&q=80",
    time: "1 h",
    level: "Médio",
    origin: "Brasil",
    desc: "Carne macia cozida com legumes — almoço de domingo simplificado.",
    steps: [
      "Sele a carne em cubos com cebola e alho.",
      "Adicione água ou caldo e cozinhe em pressão por 30 min.",
      "Acrescente batata e cenoura em rodelas.",
      "Cozinhe mais 10 min até os legumes ficarem macios.",
      "Sirva com arroz branco.",
    ],
  },
  {
    id: "bobo-camarao",
    name: "Bobó de camarão",
    meals: ["almoco"],
    region: "nordeste",
    state: "bahia",
    tags: ["peixe", "mandioca", "leite", "arroz"],
    shop: ["camarão", "mandioca ou aipim", "leite de coco", "pimentão", "tomate", "coentro", "azeite de dendê"],
    image: "https://images.unsplash.com/photo-1565557623262-b51c2513a641?w=800&q=80",
    time: "50 min",
    level: "Médio",
    origin: "Nordeste · Bahia",
    desc: "Creme de mandioca com camarão — influência baiana clássica.",
    steps: [
      "Cozinhe a mandioca e amasse até formar um purê.",
      "Refogue camarões temperados rapidamente.",
      "Misture o purê com leite de coco e legumes.",
      "Adicione os camarões e um fio de dendê.",
      "Sirva com arroz branco.",
    ],
  },
  {
    id: "arroz-feijao-frango",
    name: "Arroz, feijão e frango grelhado",
    meals: ["almoco", "janta"],
    region: "brasil",
    tags: ["arroz", "feijao", "frango", "legumes"],
    shop: ["arroz", "feijão", "peito de frango", "alho", "sal", "salada verde"],
    image: "https://images.unsplash.com/photo-1598103442097-8b74394b95c6?w=800&q=80",
    time: "40 min",
    level: "Fácil",
    origin: "Brasil",
    desc: "O trio brasileiro: arroz, feijão e frango — simples e completo.",
    steps: [
      "Cozinhe arroz e feijão separadamente.",
      "Tempere o frango com alho e sal.",
      "Grelhe o frango na frigideira ou chapa.",
      "Monte o prato com arroz, feijão e frango fatiado.",
      "Acompanhe com salada verde.",
    ],
  },

  /* ─── JANTA ─── */
  {
    id: "sopa-legumes-frango",
    name: "Sopa de legumes com frango",
    meals: ["janta"],
    region: "brasil",
    tags: ["sopa", "frango", "legumes", "macarrao"],
    shop: ["frango desfiado", "batata", "cenoura", "chuchu", "macarrão", "caldo de galinha"],
    image: "https://images.unsplash.com/photo-1621996346565-e3dbc646d9a9?w=800&q=80",
    time: "35 min",
    level: "Fácil",
    origin: "Brasil",
    desc: "Sopa leve e reconfortante — ideal para jantar sem pesar.",
    steps: [
      "Refogue cebola e alho.",
      "Adicione legumes em cubos e água ou caldo.",
      "Cozinhe até os legumes ficarem macios.",
      "Acrescente frango desfiado e macarrão pequeno.",
      "Ajuste sal e sirva quente.",
    ],
  },
  {
    id: "macarrao-manteiga-queijo",
    name: "Macarrão na manteiga com queijo",
    meals: ["janta"],
    region: "brasil",
    tags: ["macarrao", "manteiga", "queijo"],
    shop: ["macarrão espaguete ou parafuso", "manteiga", "queijo ralado", "sal", "orégano"],
    image: "https://images.unsplash.com/photo-1621996346565-e3dbc646d9a9?w=800&q=80",
    time: "20 min",
    level: "Fácil",
    origin: "Brasil",
    desc: "Jantar rápido: macarrão al dente com manteiga e queijo derretido.",
    steps: [
      "Cozinhe o macarrão em água com sal.",
      "Escorra reservando um pouco da água.",
      "Misture manteiga quente com o macarrão.",
      "Adicione queijo ralado e um pouco da água do cozimento.",
      "Finalize com orégano e sirva.",
    ],
  },
  {
    id: "omelete-pao",
    name: "Omelete recheado com pão",
    meals: ["janta", "cafe"],
    region: "brasil",
    tags: ["ovo", "queijo", "pao", "manteiga"],
    shop: ["ovos", "queijo", "pão", "manteiga", "sal", "tomate"],
    image: "https://images.unsplash.com/photo-1608039829572-78524f79c4c7?w=800&q=80",
    time: "12 min",
    level: "Fácil",
    origin: "Brasil",
    desc: "Omelete fofinho com queijo, servido com pão — jantar em minutos.",
    steps: [
      "Bata ovos com sal.",
      "Despeje na frigideira com manteiga.",
      "Adicione queijo e tomate quando começar a firmar.",
      "Dobre ao meio e doure.",
      "Sirva com pão fresco.",
    ],
  },
  {
    id: "tapioca-frango-janta",
    name: "Tapioca de frango com queijo",
    meals: ["janta", "cafe"],
    region: "nordeste",
    tags: ["tapioca", "frango", "queijo"],
    shop: ["goma de tapioca", "frango desfiado", "queijo", "manteiga"],
    image: "https://images.unsplash.com/photo-1482049016688-2d3e1b311543?w=800&q=80",
    time: "10 min",
    level: "Fácil",
    origin: "Nordeste",
    desc: "Jantar leve e regional: tapioca recheada com frango temperado.",
    steps: [
      "Tempere o frango desfiado com sal e pimenta.",
      "Faça a tapioca na frigideira quente.",
      "Recheie com frango e queijo.",
      "Dobre e doure.",
      "Sirva imediatamente.",
    ],
  },
  {
    id: "sanduiche-frango",
    name: "Sanduíche natural de frango",
    meals: ["janta"],
    region: "brasil",
    tags: ["pao", "frango", "legumes"],
    shop: ["pão de forma", "frango desfiado", "maionese", "alface", "tomate"],
    image: "https://images.unsplash.com/photo-1528735602780-2552fd46c7af?w=800&q=80",
    time: "10 min",
    level: "Fácil",
    origin: "Brasil",
    desc: "Sanduíche frio com frango e salada — prático para jantar leve.",
    steps: [
      "Misture frango desfiado com maionese e temperos.",
      "Monte o sanduíche com alface e tomate.",
      "Corte ao meio e sirva.",
    ],
  },
  {
    id: "canja-galinha",
    name: "Canja de galinha",
    meals: ["janta"],
    region: "brasil",
    tags: ["sopa", "frango", "arroz", "legumes"],
    shop: ["frango em pedaços", "arroz", "cenoura", "batata", "cheiro-verde", "alho"],
    image: "https://images.unsplash.com/photo-1604908176997-125f25cc6f3d?w=800&q=80",
    time: "50 min",
    level: "Médio",
    origin: "Brasil",
    desc: "Canja cremosa — remédio e jantar reconfortante.",
    steps: [
      "Cozinhe o frango com alho e sal até desmanchar.",
      "Retire os ossos e desfie a carne.",
      "Adicione arroz e legumes em cubos.",
      "Cozinhe até o arroz abrir e a sopa engrossar.",
      "Finalize com cheiro-verde.",
    ],
  },
  {
    id: "panelada-sergipe",
    name: "Panelada sergipana",
    meals: ["almoco", "janta"],
    region: "nordeste",
    state: "sergipe",
    tags: ["carne", "farinha", "legumes"],
    shop: ["bucho ou miúdos de boi", "tomate", "cebola", "pimentão", "coentro", "farinha de mandioca"],
    image: "https://images.unsplash.com/photo-1604908176997-125f25cc6f3d?w=800&q=80",
    time: "1 h 30",
    level: "Difícil",
    origin: "Nordeste · Sergipe",
    desc: "Prato típico sergipano com miúdos de boi cozidos — tradição nordestina.",
    steps: [
      "Lave bem e cozinhe os miúdos com limão e sal.",
      "Refogue tomate, cebola e pimentão.",
      "Adicione os miúdos cozidos e um pouco de caldo.",
      "Cozinhe em fogo baixo por 40 min.",
      "Sirva com farinha de mandioca e coentro.",
    ],
  },
  {
    id: "acaraje",
    name: "Acarajé com vatapá (versão caseira)",
    meals: ["janta", "almoco"],
    region: "nordeste",
    state: "bahia",
    tags: ["feijao", "farinha", "camarão", "frango"],
    shop: ["feijão fradinho", "cebola", "azeite de dendê", "camarão seco", "pimenta", "tomate"],
    image: "https://images.unsplash.com/photo-1565299507177-b0ac66763828?w=800&q=80",
    time: "1 h",
    level: "Difícil",
    origin: "Nordeste · Bahia",
    desc: "Bolinho de feijão frito no dendê — ícone baiano adaptado para casa.",
    steps: [
      "Deixe o feijão de molho, cozinhe e processe com cebola e sal.",
      "Modele bolinhos e frite no azeite de dendê.",
      "Prepare recheio com camarão refogado ou vatapá.",
      "Abra o acarajé ao meio e recheie.",
      "Sirva quente com pimenta.",
    ],
  },
  {
    id: "pao-queijo-cafe",
    name: "Pão de queijo com café",
    meals: ["cafe", "janta"],
    region: "sudeste",
    state: "minas gerais",
    tags: ["queijo", "pao", "cafe", "leite"],
    shop: ["pão de queijo (congelado ou polvilho)", "ovos", "queijo minas", "café", "leite"],
    image: "https://images.unsplash.com/photo-1504674900247-0877df9cc836?w=800&q=80",
    time: "25 min",
    level: "Fácil",
    origin: "Sudeste · Minas Gerais",
    desc: "Pão de queijo quentinho com café — mineiro de coração.",
    steps: [
      "Prepare a massa ou asse pães de queijo congelados.",
      "Asse em forno alto até dourar.",
      "Prepare café com leite.",
      "Sirva os pães quentes acompanhando o café.",
    ],
  },
  {
    id: "vitamina-frutas",
    name: "Vitamina de frutas com aveia",
    meals: ["cafe"],
    region: "brasil",
    tags: ["vitamina", "frutas", "banana", "leite", "aveia"],
    shop: ["banana", "leite", "aveia", "mel", "mamão ou manga"],
    image: "https://images.unsplash.com/photo-1553530666-ba11a7da3888?w=800&q=80",
    time: "5 min",
    level: "Fácil",
    origin: "Brasil",
    desc: "Vitamina cremosa de frutas com aveia — energia para começar o dia.",
    steps: [
      "Bata no liquidificador frutas, leite e aveia.",
      "Adoce com mel se quiser.",
      "Sirva gelada ou com gelo.",
    ],
  },
  {
    id: "panqueca-mel",
    name: "Panquecas com mel e frutas",
    meals: ["cafe"],
    region: "brasil",
    tags: ["waffle", "doce", "mel", "frutas", "leite", "ovo"],
    shop: ["farinha", "ovos", "leite", "mel", "banana", "manteiga"],
    image: "https://images.unsplash.com/photo-1567620905732-2d1ec7ab7445?w=800&q=80",
    time: "20 min",
    level: "Fácil",
    origin: "Brasil",
    desc: "Panquecas fofinhas com mel e frutas frescas.",
    steps: [
      "Misture farinha, ovos, leite e uma pitada de sal.",
      "Doure panquecas pequenas na manteiga.",
      "Sirva empilhadas com mel e frutas fatiadas.",
    ],
  },
  {
    id: "churrasco-mineiro",
    name: "Churrasco mineiro com farofa",
    meals: ["almoco"],
    region: "sudeste",
    state: "minas gerais",
    tags: ["churrasco", "carne", "linguica", "farinha"],
    shop: ["picanha ou costela", "linguiça", "farinha de mandioca", "alho", "sal grosso", "limão"],
    image: "https://images.unsplash.com/photo-1555939594-58d7cb561ad1?w=800&q=80",
    time: "1 h 30",
    level: "Médio",
    origin: "Sudeste · Minas Gerais",
    desc: "Carnes na brasa com farofa crocante — almoço de domingo.",
    steps: [
      "Tempere as carnes com alho e sal grosso.",
      "Grelhe na churrasqueira ou grill.",
      "Prepare farofa com farinha, manteiga e linguiça.",
      "Sirva com limão e vinagrete.",
    ],
  },
  {
    id: "estrogonofe-frango",
    name: "Estrogonofe de frango",
    meals: ["almoco", "janta"],
    region: "brasil",
    tags: ["estrogonofe", "frango", "arroz", "creme"],
    shop: ["peito de frango", "creme de leite", "molho de tomate", "ketchup", "champignon", "arroz", "batata palha"],
    image: "https://images.unsplash.com/photo-1455619452474-d2be8b1e70cd?w=800&q=80",
    time: "35 min",
    level: "Fácil",
    origin: "Brasil",
    desc: "Frango cremoso com arroz e batata palha — clássico de almoço e janta.",
    steps: [
      "Corte o frango em cubos e doure.",
      "Adicione molho de tomate e ketchup.",
      "Finalize com creme de leite e champignon.",
      "Sirva com arroz branco e batata palha.",
    ],
  },
  {
    id: "pizza-caseira",
    name: "Pizza caseira de frigideira",
    meals: ["janta"],
    region: "sudeste",
    tags: ["pizza", "queijo", "molho"],
    shop: ["massa de pizza ou pão sírio", "molho de tomate", "mussarela", "orégano", "azeitona"],
    image: "https://images.unsplash.com/photo-1513104890138-7c749659a591?w=800&q=80",
    time: "25 min",
    level: "Fácil",
    origin: "Brasil",
    desc: "Pizza rápida na frigideira — jantar prático sem forno.",
    steps: [
      "Abra a massa fina na frigideira.",
      "Espalhe molho e queijo.",
      "Tampe e cozinhe em fogo baixo até derreter.",
      "Finalize com orégano e azeitonas.",
    ],
  },
  {
    id: "hamburguer-caseiro",
    name: "Hambúrguer artesanal caseiro",
    meals: ["janta"],
    region: "brasil",
    tags: ["hamburguer", "carne", "pao", "queijo"],
    shop: ["carne moída", "pão de hambúrguer", "queijo", "alface", "tomate", "cebola"],
    image: "https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=800&q=80",
    time: "25 min",
    level: "Fácil",
    origin: "Brasil",
    desc: "Hambúrguer suculento montado em casa.",
    steps: [
      "Tempere a carne e modele os discos.",
      "Grelhe 3–4 min de cada lado.",
      "Derreta o queijo por cima.",
      "Monte com salada e pão tostado.",
    ],
  },
  {
    id: "pastel-forno",
    name: "Pastel de forno de frango",
    meals: ["janta", "cafe"],
    region: "sudeste",
    tags: ["pastel", "salgado", "frango"],
    shop: ["massa de pastel", "frango desfiado", "requeijão", "milho", "ovo para pincelar"],
    image: "https://images.unsplash.com/photo-1551183053-bf91a1d81141?w=800&q=80",
    time: "30 min",
    level: "Fácil",
    origin: "Sudeste",
    desc: "Pastel assado recheado — crocante sem fritura.",
    steps: [
      "Recheie discos de massa com frango e requeijão.",
      "Feche e pincele gema.",
      "Asse em forno alto até dourar.",
      "Sirva quente.",
    ],
  },
  {
    id: "escondidinho-camarao",
    name: "Escondidinho de camarão",
    meals: ["janta", "almoco"],
    region: "nordeste",
    tags: ["escondidinho", "camarao", "mandioca", "queijo"],
    shop: ["camarão", "purê de mandioca", "queijo", "leite de coco", "cebola", "pimentão"],
    image: "https://images.unsplash.com/photo-1476124369491-e7addf5db371?w=800&q=80",
    time: "45 min",
    level: "Médio",
    origin: "Nordeste",
    desc: "Camada de camarão refogado coberta com purê de mandioca gratinado.",
    steps: [
      "Refogue camarões com temperos.",
      "Monte em refratário: camarão e purê por cima.",
      "Polvilhe queijo e gratine.",
      "Sirva quente.",
    ],
  },
  {
    id: "yakisoba-caseiro",
    name: "Yakisoba caseiro",
    meals: ["janta"],
    region: "sudeste",
    tags: ["yakisoba", "macarrao", "frango", "legumes"],
    shop: ["macarrão para yakisoba", "frango", "repolho", "cenoura", "molho shoyu", "gengibre"],
    image: "https://images.unsplash.com/photo-1563379926898-05f4575a45d8?w=800&q=80",
    time: "30 min",
    level: "Fácil",
    origin: "Brasil",
    desc: "Macarrão salteado com legumes e frango — jantar oriental brasileiro.",
    steps: [
      "Cozinhe o macarrão al dente.",
      "Salteie frango e legumes em fogo alto.",
      "Adicione macarrão e molho shoyu.",
      "Finalize com gengibre e cebolinha.",
    ],
  },
  {
    id: "risoto-simples",
    name: "Risoto de frango com legumes",
    meals: ["janta"],
    region: "sul",
    tags: ["risoto", "arroz", "frango", "legumes", "queijo"],
    shop: ["arroz arbóreo", "frango", "caldo de galinha", "queijo parmesão", "cebola", "abobrinha"],
    image: "https://images.unsplash.com/photo-1476124369491-e7addf5db371?w=800&q=80",
    time: "40 min",
    level: "Médio",
    origin: "Sul",
    desc: "Risoto cremoso com frango — jantar especial em uma panela.",
    steps: [
      "Refogue cebola e arroz.",
      "Adicione caldo quente aos poucos mexendo sempre.",
      "Incorpore frango cozido e legumes.",
      "Finalize com parmesão e manteiga.",
    ],
  },

  /* ─── MAIS CAFÉ DA MANHÃ ─── */
  {
    id: "bolo-fuba-queijo",
    name: "Bolo de fubá com queijo",
    meals: ["cafe"],
    region: "sudeste",
    state: "minas gerais",
    tags: ["doce", "queijo", "cafe", "leite", "bolo"],
    shop: ["fubá", "ovos", "leite", "queijo minas", "açúcar", "óleo", "fermento"],
    image: "https://images.unsplash.com/photo-1504674900247-0877df9cc836?w=800&q=80",
    time: "45 min",
    level: "Fácil",
    origin: "Sudeste · Minas Gerais",
    desc: "Bolo fofinho de fubá com pedaços de queijo — clássico mineiro no café.",
    steps: [
      "Bata ovos, açúcar, leite e óleo.",
      "Misture fubá, fermento e queijo em cubos.",
      "Despeje em forma untada.",
      "Asse em forno médio por 35–40 min.",
      "Sirva morno com café coado.",
    ],
  },
  {
    id: "mingau-aveia-banana",
    name: "Mingau de aveia com banana",
    meals: ["cafe"],
    region: "brasil",
    tags: ["aveia", "banana", "leite", "mel", "mingau"],
    shop: ["aveia", "leite", "banana", "mel", "canela"],
    image: "https://images.unsplash.com/photo-1525351484163-7529414344d8?w=800&q=80",
    time: "10 min",
    level: "Fácil",
    origin: "Brasil",
    desc: "Mingau cremoso de aveia com banana amassada — rápido e nutritivo.",
    steps: [
      "Aqueça leite com aveia em fogo baixo.",
      "Mexa até engrossar, cerca de 5 min.",
      "Amasse a banana e incorpore.",
      "Adoce com mel e polvilhe canela.",
      "Sirva quente.",
    ],
  },
  {
    id: "pao-requeijao-presunto",
    name: "Pão com requeijão e presunto",
    meals: ["cafe", "janta"],
    region: "brasil",
    tags: ["pao", "queijo", "presunto", "manteiga"],
    shop: ["pão francês ou de forma", "requeijão", "presunto", "manteiga", "orégano"],
    image: "https://images.unsplash.com/photo-1482049016688-2d3e1b311543?w=800&q=80",
    time: "8 min",
    level: "Fácil",
    origin: "Brasil",
    desc: "Sanduíche quente simples: pão, requeijão cremoso e presunto na chapa.",
    steps: [
      "Corte o pão ao meio.",
      "Passe requeijão nos dois lados.",
      "Adicione presunto e feche.",
      "Doure na manteiga na frigideira.",
      "Sirva quente com orégano se quiser.",
    ],
  },
  {
    id: "iogurte-granola-frutas",
    name: "Iogurte com granola e frutas",
    meals: ["cafe"],
    region: "brasil",
    tags: ["iogurte", "granola", "frutas", "mel", "banana"],
    shop: ["iogurte natural", "granola", "banana", "morango ou mamão", "mel"],
    image: "https://images.unsplash.com/photo-1553530666-ba11a7da3888?w=800&q=80",
    time: "5 min",
    level: "Fácil",
    origin: "Brasil",
    desc: "Taça de iogurte com granola crocante e frutas frescas.",
    steps: [
      "Coloque iogurte em uma taça.",
      "Adicione granola por cima.",
      "Decore com frutas fatiadas.",
      "Finalize com fio de mel.",
      "Sirva na hora.",
    ],
  },
  {
    id: "suco-laranja-caseiro",
    name: "Suco de laranja com pão e manteiga",
    meals: ["cafe"],
    region: "brasil",
    tags: ["suco", "frutas", "pao", "manteiga"],
    shop: ["laranjas", "açúcar", "pão", "manteiga"],
    image: "https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?w=800&q=80",
    time: "8 min",
    level: "Fácil",
    origin: "Brasil",
    desc: "Suco de laranja espremido na hora com pão na manteiga — café leve e fresco.",
    steps: [
      "Esprema as laranjas e adoce se necessário.",
      "Sirva gelado ou com gelo.",
      "Toste o pão na manteiga.",
      "Monte a mesa com suco e pão quente.",
    ],
  },
  {
    id: "cuscuz-carne-seca",
    name: "Cuscuz com carne seca e manteiga",
    meals: ["cafe"],
    region: "nordeste",
    state: "pernambuco",
    tags: ["cuscuz", "carne", "manteiga", "ovo"],
    shop: ["cuscuz de milho", "carne seca", "manteiga", "ovos", "coentro", "cebola"],
    image: "https://images.unsplash.com/photo-1546069901-ba9599a7e63c?w=800&q=80",
    time: "35 min",
    level: "Médio",
    origin: "Nordeste · Pernambuco",
    desc: "Cuscuz nordestino com carne seca desfiada — café da manhã forte e tradicional.",
    steps: [
      "Dessalgue e cozinhe a carne seca até desfiar.",
      "Refogue a carne com cebola.",
      "Prepare o cuscuz no vapor.",
      "Sirva o cuscuz com carne por cima e manteiga.",
      "Acompanhe com ovo frito se quiser.",
    ],
  },
  {
    id: "cha-biscoito",
    name: "Chá com biscoitos e torradas",
    meals: ["cafe"],
    region: "brasil",
    tags: ["cha", "biscoito", "torrada", "mel", "manteiga"],
    shop: ["chá de camomila ou preto", "biscoito", "torrada", "mel", "manteiga"],
    image: "https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?w=800&q=80",
    time: "7 min",
    level: "Fácil",
    origin: "Brasil",
    desc: "Café da manhã leve: chá quente com torradas, mel e biscoitos.",
    steps: [
      "Prepare o chá na infusão desejada.",
      "Toste pães ou use torradas prontas.",
      "Passe manteiga e mel nas torradas.",
      "Sirva com biscoitos para acompanhar.",
    ],
  },

  /* ─── MAIS ALMOÇO ─── */
  {
    id: "picadinho-arroz",
    name: "Picadinho de carne com arroz",
    meals: ["almoco"],
    region: "sudeste",
    state: "sao paulo",
    tags: ["carne", "arroz", "legumes", "feijao"],
    shop: ["carne moída ou acém em cubos", "arroz", "tomate", "cebola", "batata", "cheiro-verde"],
    image: "https://images.unsplash.com/photo-1600891964092-4316c288032e?w=800&q=80",
    time: "45 min",
    level: "Médio",
    origin: "Sudeste · São Paulo",
    desc: "Carne cozida em cubos com legumes e caldo espesso — almoço de panela.",
    steps: [
      "Sele a carne com cebola e alho.",
      "Adicione tomate, batata e água.",
      "Cozinhe em fogo baixo até a carne ficar macia.",
      "Ajuste sal e finalize com cheiro-verde.",
      "Sirva com arroz branco e feijão.",
    ],
  },
  {
    id: "frango-passarinho",
    name: "Frango à passarinho com mandioca",
    meals: ["almoco"],
    region: "sudeste",
    tags: ["frango", "mandioca", "salada", "arroz"],
    shop: ["frango em pedaços", "alho", "limão", "mandioca", "arroz", "salada verde"],
    image: "https://images.unsplash.com/photo-1598103442097-8b74394b95c6?w=800&q=80",
    time: "50 min",
    level: "Médio",
    origin: "Sudeste",
    desc: "Frango frito crocante com alho e limão, mandioca cozida e arroz.",
    steps: [
      "Tempere o frango com alho, limão e sal.",
      "Frite ou asse até dourar e ficar crocante.",
      "Cozinhe a mandioca em cubos.",
      "Prepare arroz branco e salada.",
      "Sirva tudo junto com limão a mais.",
    ],
  },
  {
    id: "peixe-frito-pirao",
    name: "Peixe frito com pirão",
    meals: ["almoco"],
    region: "nordeste",
    state: "sergipe",
    tags: ["peixe", "farinha", "arroz", "legumes"],
    shop: ["peixe inteiro ou filé", "farinha de mandioca", "limão", "alho", "arroz", "salada"],
    image: "https://images.unsplash.com/photo-1519708227418-c8fd9a32b7a2?w=800&q=80",
    time: "40 min",
    level: "Médio",
    origin: "Nordeste · Sergipe",
    desc: "Peixe frito dourado com pirão de farinha — almoço costeiro clássico.",
    steps: [
      "Tempere o peixe com limão, alho e sal.",
      "Frite em óleo quente até dourar.",
      "Use o caldo do peixe para fazer o pirão com farinha.",
      "Prepare arroz branco e salada.",
      "Sirva o peixe com pirão e arroz.",
    ],
  },
  {
    id: "salpicao-frango",
    name: "Salpicão de frango",
    meals: ["almoco"],
    region: "brasil",
    tags: ["frango", "salada", "legumes", "maionese"],
    shop: ["frango cozido", "cenoura ralada", "milho", "ervilha", "maionese", "batata palha", "limão"],
    image: "https://images.unsplash.com/photo-1546069901-ba9599a7e63c?w=800&q=80",
    time: "30 min",
    level: "Fácil",
    origin: "Brasil",
    desc: "Salpicão cremoso com frango desfiado — almoço refrescante e prático.",
    steps: [
      "Desfie o frango cozido e tempere.",
      "Misture cenoura, milho, ervilha e maionese.",
      "Acerte sal, pimenta e limão.",
      "Finalize com batata palha na hora de servir.",
      "Acompanhe com arroz ou pão.",
    ],
  },
  {
    id: "strogonoff-carne",
    name: "Strogonoff de carne",
    meals: ["almoco", "janta"],
    region: "brasil",
    tags: ["carne", "estrogonofe", "arroz", "creme"],
    shop: ["carne em tiras", "creme de leite", "molho de tomate", "champignon", "arroz", "batata palha"],
    image: "https://images.unsplash.com/photo-1455619452474-d2be8b1e70cd?w=800&q=80",
    time: "35 min",
    level: "Fácil",
    origin: "Brasil",
    desc: "Carne em tiras no molho cremoso — versão clássica do strogonoff.",
    steps: [
      "Sele a carne em tiras rápido na frigideira.",
      "Adicione molho de tomate e champignon.",
      "Finalize com creme de leite fora do fogo.",
      "Sirva com arroz branco e batata palha.",
    ],
  },
  {
    id: "macarronada-sugo",
    name: "Macarronada ao sugo com carne",
    meals: ["almoco"],
    region: "sudeste",
    tags: ["macarrao", "carne", "queijo", "molho"],
    shop: ["macarrão penne ou parafuso", "carne moída", "molho de tomate", "cebola", "alho", "queijo ralado"],
    image: "https://images.unsplash.com/photo-1621996346565-e3dbc646d9a9?w=800&q=80",
    time: "35 min",
    level: "Fácil",
    origin: "Sudeste",
    desc: "Macarrão com molho de carne moída — almoço farto e familiar.",
    steps: [
      "Cozinhe o macarrão al dente.",
      "Refogue carne moída com cebola e alho.",
      "Adicione molho de tomate e cozinhe 10 min.",
      "Misture com o macarrão ou sirva por cima.",
      "Polvilhe queijo ralado.",
    ],
  },
  {
    id: "parmegiana-frango",
    name: "Filé de frango à parmegiana",
    meals: ["almoco", "janta"],
    region: "sul",
    state: "rio grande do sul",
    tags: ["frango", "queijo", "arroz", "molho"],
    shop: ["peito de frango", "farinha de rosca", "molho de tomate", "mussarela", "arroz", "batata frita"],
    image: "https://images.unsplash.com/photo-1565299624946-b28f40a0ae38?w=800&q=80",
    time: "40 min",
    level: "Médio",
    origin: "Sul",
    desc: "Frango empanado com molho e queijo gratinado — clássico de almoço.",
    steps: [
      "Empane o frango em farinha, ovo e rosca.",
      "Frite ou asse até dourar.",
      "Cubra com molho de tomate e mussarela.",
      "Gratine no forno até derreter.",
      "Sirva com arroz e batata.",
    ],
  },
  {
    id: "vatapa-arroz",
    name: "Vatapá com arroz branco",
    meals: ["almoco"],
    region: "nordeste",
    state: "bahia",
    tags: ["feijao", "camarao", "arroz", "farinha"],
    shop: ["pão francês seco", "leite de coco", "amendoim", "camarão", "azeite de dendê", "arroz", "pimenta"],
    image: "https://images.unsplash.com/photo-1565557623262-b51c2513a641?w=800&q=80",
    time: "55 min",
    level: "Médio",
    origin: "Nordeste · Bahia",
    desc: "Creme baiano de pão, coco e camarão — almoço regional intenso.",
    steps: [
      "Deixe o pão de molho e bata com leite de coco.",
      "Refogue cebola, pimenta e camarão.",
      "Adicione o creme de pão e amendoim.",
      "Finalize com dendê e coentro.",
      "Sirva com arroz branco.",
    ],
  },

  /* ─── MAIS JANTA ─── */
  {
    id: "misto-quente",
    name: "Misto quente na frigideira",
    meals: ["janta", "cafe"],
    region: "brasil",
    tags: ["pao", "queijo", "presunto", "manteiga"],
    shop: ["pão de forma", "presunto", "mussarela", "manteiga"],
    image: "https://images.unsplash.com/photo-1528735602780-2552fd46c7af?w=800&q=80",
    time: "8 min",
    level: "Fácil",
    origin: "Brasil",
    desc: "Sanduíche quente de presunto e queijo — jantar em minutos.",
    steps: [
      "Monte pão, presunto e queijo.",
      "Passe manteiga por fora.",
      "Doure na frigideira dos dois lados.",
      "Corte ao meio e sirva quente.",
    ],
  },
  {
    id: "batata-recheada",
    name: "Batata recheada no forno",
    meals: ["janta"],
    region: "brasil",
    tags: ["carne", "queijo", "legumes"],
    shop: ["batata inglesa grande", "carne moída", "mussarela", "cebola", "creme de leite", "cheiro-verde"],
    image: "https://images.unsplash.com/photo-1512058564366-18510be2db19?w=800&q=80",
    time: "50 min",
    level: "Médio",
    origin: "Brasil",
    desc: "Batata assada recheada com carne e queijo — jantar completo.",
    steps: [
      "Asse as batatas até ficarem macias.",
      "Refogue carne moída com cebola e temperos.",
      "Abra as batatas e recheie com a carne.",
      "Cubra com queijo e creme de leite.",
      "Gratine e sirva com salada.",
    ],
  },
  {
    id: "wrap-frango",
    name: "Wrap de frango com salada",
    meals: ["janta"],
    region: "brasil",
    tags: ["frango", "pao", "legumes", "salada"],
    shop: ["massa de wrap ou tortilha", "frango grelhado", "alface", "tomate", "cream cheese", "milho"],
    image: "https://images.unsplash.com/photo-1528735602780-2552fd46c7af?w=800&q=80",
    time: "15 min",
    level: "Fácil",
    origin: "Brasil",
    desc: "Wrap enrolado com frango e vegetais — jantar leve e prático.",
    steps: [
      "Grelhe e fatie o frango.",
      "Espalhe cream cheese na tortilha.",
      "Adicione frango, alface, tomate e milho.",
      "Enrole firme e corte ao meio.",
      "Sirva frio ou levemente aquecido.",
    ],
  },
  {
    id: "frango-xadrez",
    name: "Frango xadrez com arroz",
    meals: ["janta", "almoco"],
    region: "brasil",
    tags: ["frango", "arroz", "legumes", "molho"],
    shop: ["peito de frango", "pimentão", "cebola", "tomate", "molho shoyu", "arroz", "amido de milho"],
    image: "https://images.unsplash.com/photo-1563379926898-05f4575a45d8?w=800&q=80",
    time: "30 min",
    level: "Fácil",
    origin: "Brasil",
    desc: "Frango salteado com legumes e molho agridoce — jantar oriental brasileiro.",
    steps: [
      "Corte o frango em cubos e tempere.",
      "Salteie frango, pimentão, cebola e tomate.",
      "Adicione shoyu e um pouco de amido dissolvido.",
      "Cozinhe até engrossar levemente.",
      "Sirva com arroz branco.",
    ],
  },
  {
    id: "caldo-verde-simples",
    name: "Caldo verde simplificado",
    meals: ["janta"],
    region: "sul",
    state: "santa catarina",
    tags: ["sopa", "linguica", "legumes", "batata"],
    shop: ["couve manteiga", "batata", "linguiça calabresa", "cebola", "alho", "caldo de legumes"],
    image: "https://images.unsplash.com/photo-1621996346565-e3dbc646d9a9?w=800&q=80",
    time: "35 min",
    level: "Fácil",
    origin: "Sul · Santa Catarina",
    desc: "Sopa cremosa de batata com couve e linguiça — jantar reconfortante.",
    steps: [
      "Cozinhe batatas e bata metade para engrossar.",
      "Refogue linguiça em rodelas.",
      "Adicione caldo, batatas e couve bem picada.",
      "Cozinhe 10 min em fogo baixo.",
      "Sirva quente com pimenta do reino.",
    ],
  },
  {
    id: "salada-atum",
    name: "Salada de atum com pão",
    meals: ["janta"],
    region: "brasil",
    tags: ["salada", "peixe", "pao", "legumes"],
    shop: ["atum em lata", "milho", "ervilha", "maionese", "alface", "tomate", "pão"],
    image: "https://images.unsplash.com/photo-1546069901-ba9599a7e63c?w=800&q=80",
    time: "12 min",
    level: "Fácil",
    origin: "Brasil",
    desc: "Salada fresca de atum — jantar leve sem fogão.",
    steps: [
      "Escorra o atum e misture com milho, ervilha e maionese.",
      "Monte cama de alface e tomate.",
      "Coloque a mistura de atum por cima.",
      "Sirva com pão ou torradas.",
    ],
  },
  {
    id: "macarrao-alho-oleo",
    name: "Macarrão alho e óleo com ovo",
    meals: ["janta"],
    region: "brasil",
    tags: ["macarrao", "ovo", "manteiga", "queijo"],
    shop: ["macarrão espaguete", "alho", "azeite", "ovos", "salsinha", "queijo parmesão"],
    image: "https://images.unsplash.com/photo-1551183053-bf91a1d81141?w=800&q=80",
    time: "18 min",
    level: "Fácil",
    origin: "Brasil",
    desc: "Macarrão simples com alho dourado e ovo frito por cima.",
    steps: [
      "Cozinhe o macarrão al dente.",
      "Dourar alho no azeite em fogo baixo.",
      "Misture o macarrão escorrido com o alho.",
      "Frite ovos com gema mole.",
      "Sirva com parmesão e salsinha.",
    ],
  },
  {
    id: "lasanha-frigideira",
    name: "Lasanha de frigideira rápida",
    meals: ["janta"],
    region: "brasil",
    tags: ["macarrao", "carne", "queijo", "molho"],
    shop: ["massa para lasanha ou biscoito salgado", "carne moída", "molho de tomate", "mussarela", "creme de leite"],
    image: "https://images.unsplash.com/photo-1476124369491-e7addf5db371?w=800&q=80",
    time: "35 min",
    level: "Médio",
    origin: "Brasil",
    desc: "Camadas de massa, carne e queijo na frigideira — lasanha sem forno.",
    steps: [
      "Refogue carne moída com molho de tomate.",
      "Monte camadas de massa, carne e queijo na frigideira.",
      "Tampe e cozinhe em fogo baixo por 20 min.",
      "Finalize com creme de leite e queijo.",
      "Deixe descansar 5 min antes de servir.",
    ],
  },
  {
    id: "tapioca-doce-coco",
    name: "Tapioca doce de coco e leite condensado",
    meals: ["janta", "cafe"],
    region: "nordeste",
    tags: ["tapioca", "doce", "leite", "coco"],
    shop: ["goma de tapioca", "coco ralado", "leite condensado", "manteiga"],
    image: "https://images.unsplash.com/photo-1567620905732-2d1ec7ab7445?w=800&q=80",
    time: "10 min",
    level: "Fácil",
    origin: "Nordeste",
    desc: "Tapioca doce recheada com coco e leite condensado — jantar leve e nordestino.",
    steps: [
      "Faça a tapioca fina na frigideira.",
      "Recheie com coco e leite condensado.",
      "Dobre e doure levemente.",
      "Sirva quente com manteiga opcional.",
    ],
  },
];
